name: deploy to lambda function for zelda home

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1
          function_name: zeldaHome
          zip_file: bundle.zip
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build zelda_user/index.mjs
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=zeldaHome --zip-file=fileb://deploy.zip
